/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/laptop_remote/static/**/*.{html,js}",
    "/home/sathybalan/Downloads/stitch_apple_design_system_redesign(1)/stitch_apple_design_system_redesign/**/*.html"
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#39393b",
        "on-surface-variant": "#c7c4d7",
        "surface-dim": "#131315",
        "inverse-primary": "#4d4ad5",
        "on-background": "#e4e2e4",
        "on-primary-fixed-variant": "#332dbc",
        "outline": "#918fa0",
        "outline-variant": "#464554",
        "surface-variant": "#353437",
        "on-surface": "#e4e2e4",
        "on-tertiary-fixed-variant": "#00531a",
        "secondary-container": "#3e90ff",
        "on-secondary-container": "#002957",
        "primary-container": "#5e5ce6",
        "on-secondary": "#003064",
        "primary": "#c2c1ff",
        "on-primary-container": "#f4f1ff",
        "surface-container-low": "#1b1b1d",
        "primary-fixed-dim": "#c2c1ff",
        "surface": "#131315",
        "surface-container-highest": "#353437",
        "inverse-on-surface": "#303032",
        "primary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#aac7ff",
        "tertiary": "#47e266",
        "on-secondary-fixed-variant": "#00468d",
        "on-primary-fixed": "#0c006b",
        "surface-tint": "#c2c1ff",
        "secondary": "#aac7ff",
        "on-tertiary": "#003910",
        "surface-container-lowest": "#0e0e10",
        "on-tertiary-fixed": "#002106",
        "surface-container-high": "#2a2a2c",
        "tertiary-fixed-dim": "#47e266",
        "error": "#ffb4ab",
        "on-tertiary-container": "#cdffca",
        "inverse-surface": "#e4e2e4",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary-fixed": "#6cff82",
        "surface-container": "#1f1f21",
        "tertiary-container": "#00802d",
        "on-primary": "#1800a7",
        "background": "#131315",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#001b3e",
        "secondary-fixed": "#d6e3ff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "margin": "1.5rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "body-sm": ["Geist", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "headline-sm": ["Sora", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "headline-md": ["Sora", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "headline-lg": ["Sora", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "caption": ["Geist", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "label-sm": ["Geist", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Sora", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "headline-xl": ["Sora", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "body-lg": ["Geist", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "headline-xl-mobile": ["Sora", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "label-md": ["Geist", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
        "body-md": ["Geist", "-apple-system", "BlinkMacSystemFont", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "-0.08px", fontWeight: "400" }],
        "headline-sm": ["17px", { lineHeight: "22px", letterSpacing: "-0.40px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.40px", fontWeight: "600" }],
        "headline-lg": ["26px", { lineHeight: "32px", letterSpacing: "-0.24px", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "16px", letterSpacing: "0.00px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06px", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.20px", fontWeight: "700" }],
        "headline-xl": ["34px", { lineHeight: "42px", letterSpacing: "0.38px", fontWeight: "700" }],
        "body-lg": ["17px", { lineHeight: "24px", letterSpacing: "-0.35px", fontWeight: "400" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "0.32px", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02px", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "21px", letterSpacing: "-0.20px", fontWeight: "400" }],
      }
    }
  }
};
